apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web-app
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app
    spec:
      containers:
      - image: ashok25/flaskapp:v2.0
        name: flask-app
        ports:
        - containerPort: 4080
