---
- name: Create Infra for K8-cluster
  hosts: localhost
  gather_facts: False
  vars:
    keypair: aws-key
    instance_type: t2.micro
    security_group: default
    image: ami-0eb89db7593b5d434
    region: eu-west-2
    subnet: subnet-082213e51ccfdcaa4 
  tasks:
    - name: Launch master instance
      ec2:
         count: 1 
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         instance_tags:
            Name: Devops-Master-{{item}}
            environment: ops
            node_type: master
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2
      with_items:
         - 1
    - name: Launch node instance
      ec2:
         count: 2 
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         instance_tags:
            Name: Devops-Node-{{item}}
            environment: ops 
            node_type: node
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      register: ec2
      with_items:
         - 1
         - 2
